connections:
  source_env_var: PROD_ORA_SW_CONN_STR
  source_type: oracle
  target_env_var: PROD_BQ_ALL_CONN_STR
  target_type: bigquery

alerts:
  routes:
    - kind: gchat
      mode: card # card or text
      # send_all_checks: true  # send all checks or only fails to alert

tables:
  - name: CLIENT_VALIDATION    
    source:
      table: SEAWARE.CLIENT
    target:
      table: prod-shore.nbx_parse.hvtb_parse_sw_rpl_client
    checks:
      - type: aggregations
        tolerance_pct: 5.0          # percentage tolerance: allow up to 1% difference
        rules:
          - method: distinct_count    # Distinct count <column>
            source_col: CLIENT_ID
            target_column: client_id

###########################################################################

  - name: RES_GUEST_VALIDATION    
    source:
      table: SEAWARE.RES_GUEST
    target:
      table: prod-shore.nbx_parse.hvtb_parse_sw_rpl_res_guest
    checks:
      - type: aggregations
        tolerance_pct: 5.0          # percentage tolerance: allow up to 1% difference
        rules:
          - method: distinct_count    # Distinct count <column>
            source_col: GUEST_ID
            target_column: guest_id

##########################################################################

  - name: RES_HEADER_VALIDATION    
    source:
      table: SEAWARE.RES_HEADER
    target:
      table: prod-shore.nbx_parse.hvtb_parse_sw_rpl_res_header
    checks:
      - type: aggregations
        tolerance_pct: 5.0          # percentage tolerance: allow up to 1% difference
        rules:
          - method: distinct_count    # Distinct count <column>
            source_col: RES_ID
            target_column: res_id

########################################################################

  - name: RES_INVOICE_ITEM_VALIDATION
    source:
      table: SEAWARE.RES_INVOICE_ITEM
    target:
      query: |
        SELECT *
        FROM (
          SELECT
            res_invoice_item_id,
            op
          FROM prod-shore.nbx_parse.hvtb_parse_sw_rpl_res_invoice_item
          QUALIFY ROW_NUMBER() OVER (
            PARTITION BY res_invoice_item_id
            ORDER BY ts_ms DESC, lsn DESC
          ) = 1
        )
        WHERE op != 'd'
    checks:
      - type: aggregations
        tolerance_pct: 5.0             # allow up to 1% difference
        rules:
          - method: distinct_count
            source_column: RES_INVOICE_ITEM_ID
            target_column: res_invoice_item_id

########################################################################

  - name: RES_INVOICE_CANC_VALIDATION    
    source:
      table: SEAWARE.RES_INVOICE_CANC
    target:
      table: prod-shore.nbx_parse.hvtb_parse_sw_rpl_res_invoice_canc
    checks:
      - type: aggregations
        tolerance_pct: 5.0          
        rules:
          - method: distinct_count    # Distinct count <column>
            source_col: RES_INVOICE_ITEM_ID
            target_column: res_invoice_item_id

# run example:
# python -m  src.main --filetype yaml --config-file sw_nbx_validation --env prod --run_label oracle_tables_testing 