-- =====================================================================
-- Data Quality Framework (DQF) core monitoring tables for BigQuery
-- Replace `cert-shore-295415` with your actual GCP project ID.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) Create monitoring dataset (schema)
-- ---------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cert-shore-295415.dqf_monitoring`;

-- ---------------------------------------------------------------------
-- 2) Run-level log table: one row per DQF run
--    - Used to track overall status of each run (PASS/FAIL/SKIP counts)
--    - Good entry point for dashboards and daily monitoring
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `cert-shore-295415.dqf_monitoring.dqf_runs` (
  -- Unique identifier generated by DQF for each run
  run_id           STRING  NOT NULL,

  -- Environment label, e.g. 'prod', 'cert', 'dev'
  env              STRING,

  -- Logical label for the run, e.g. 'nightly_sw', 'testing'
  run_label        STRING,

  -- Timestamps when the run started and finished
  started_at       TIMESTAMP,
  finished_at      TIMESTAMP,

  -- Overall status for the run: e.g. 'PASS', 'FAIL', 'PARTIAL'
  overall_status   STRING,

  -- Aggregated check counts for this run
  pass_count       INT64,
  fail_count       INT64,
  skip_count       INT64,

  -- Number of tables that were processed in this run
  table_count      INT64,

  -- Optional Airflow identifiers (if executed from Airflow)
  dag_id           STRING,
  task_id          STRING,

  -- Optional short JSON or text payload with extra metadata/context
  extra_context    STRING,

  -- Record creation timestamp
  created_at       TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------
-- 3) Check-level results table: one row per check/rule
--    - Stores normalized results for each table/check/rule combination
--    - Used for detailed debugging, dashboards and audit trails
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `cert-shore-295415.dqf_monitoring.dqf_check_results` (
  -- Foreign key to dqf_runs.run_id
  run_id              STRING  NOT NULL,

  -- Logical table name from the DQF config (not necessarily physical name)
  table_name          STRING,

  -- Type of check: e.g. 'row_count', 'aggregations', 'group_aggregations'
  check_type          STRING,

  -- Optional human-friendly name for the check (if configured)
  check_name          STRING,

  -- Rule index or identifier within the check (e.g. rules[0], rules[1])
  rule_id             INT64,

  -- Result status for this rule: 'PASS', 'FAIL', 'SKIP'
  status              STRING,

  -- Optional severity level: e.g. 'INFO', 'WARNING', 'CRITICAL'
  severity            STRING,

  -- Method used by the check: e.g. 'count', 'max', 'sum', 'stats_compare'
  method              STRING,

  -- Logical metric name: e.g. 'count', 'sum:AMOUNT', 'row_count'
  metric_name         STRING,

  -- Column that this rule was applied to (if applicable)
  column_name         STRING,

  -- Group key for partitioned/grouped checks
  -- Example: a bucket label such as '2024-01' or 'sail_date=2025-11'
  group_key           STRING,

  -- Period information (mainly for stats/time-based checks)
  period_granularity  STRING,        -- e.g. 'day', 'week', 'month', 'year'
  period_start        TIMESTAMP,     -- start of the bucket
  period_end          TIMESTAMP,     -- end of the bucket
  period_key          STRING,        -- e.g. '2024-01', '2025-11-21'

  -- Numeric values from source and target sides (if applicable)
  source_value        FLOAT64,
  target_value        FLOAT64,

  -- Absolute and percentage difference between source and target
  diff_abs            FLOAT64,       -- |source_value - target_value|
  diff_pct            FLOAT64,       -- 100 * diff_abs / max(|target|, eps)

  -- URI to a CSV file (in Cloud Storage) with detailed mismatches
  -- Example: 'gs://bucket/dqf/mismatch/run_id=.../table=.../ids.csv'
  mismatch_csv_uri    STRING,

  -- Reference to a stats table or view used in comparison (optional)
  stats_table_ref     STRING,

  -- Optional small JSON/text payload with extra info about the check
  extra_context       STRING,

  -- Record creation timestamp
  created_at          TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------
-- 4) Table statistics table: per-table / per-period stats for source/target
--    - Stores aggregated metrics (counts, sums, averages, etc.) for each
--      time bucket and side ('source' vs 'target')
--    - Used by higher-level "stats_compare" logic
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `cert-shore-295415.dqf_monitoring.dqf_table_stats` (
  -- DQF run that produced this stats row (optional but useful for tracing)
  run_id             STRING,

  -- Environment label, e.g. 'prod', 'cert', 'dev'
  env                STRING,

  -- Logical table name for which stats are computed
  table_name         STRING NOT NULL,

  -- Side for which stats are computed: 'source' or 'target'
  side               STRING NOT NULL,

  -- Name of the time column used for bucketing (e.g. 'SAIL_DATE_FROM')
  time_column        STRING,

  -- Granularity of the period: 'day', 'week', 'month', 'year', etc.
  period_granularity STRING,

  -- Time interval covered by this bucket
  period_start       TIMESTAMP,
  period_end         TIMESTAMP,

  -- Human-friendly bucket key, e.g. '2024-01', '2025-11-21'
  period_key         STRING,

  -- Metric name: e.g. 'count', 'sum:AMOUNT', 'avg:PRICE'
  metric_name        STRING NOT NULL,

  -- Column on which the metric is computed (if applicable)
  column_name        STRING,

  -- Numeric value of the metric
  metric_value       FLOAT64,

  -- Convenience field for row counts (can mirror 'count' metric)
  row_count          INT64,

  -- When this stats row was computed
  computed_at        TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP()
);